# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ea69c2b4430007aee345c91b8d7b786dfcdac7ebd64d63a102d73839ff65a247705c0aea0b2e7c8b4e4debd0b55b88609b837a15547586f43676300fe3daf58

test:
  secret_key_base: 46743e6d33a9178c8c2dab1a429cab8942a3a8ea66ec1f58e3b51c7ad1f28ebae206c68fd1559944bbe88d40623676c269cbb29d9f9e264481ab495f014c90a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
